### PR TITLE
[All] Replace qsort with faster std sort

### PR DESCRIPTION
**Pull request by noelchalmers**

### CODE REVIEW

**Comment by tcew** [comment]
Does this noticeably speed up preprocessing ? 

I found mixed results when experimenting with std::sort for matrix assembly.

**Comment by noelchalmers** [comment]
It probably takes pretty big sorts to notice a major difference. At least with std::sort the compiler has more opportunity for optimizations. Even if it's similar in runtime, I find the syntax with passing the comparison function as a lambda to be more clear than having a bunch of static comparison functions laying around.

**Comment by tcew** [comment]
Two things to contemplate:

1. It adda one more set of  C++ concepts for students to grasp. 

2. Eventually I think we should move all the preprocessing stuff on device, including the sort based topology methods. This will be important for adaptivity, remeshing, & moving mesh stuff where topology changes frequently. The standard library sort is not portable for on device and I have reservations about importing thrust or similar given their complexity.

I was able to refactor matrix assembly to avoid global sorts - perhaps we can do something smarter with topology too?

**Comment by noelchalmers** [comment]
I agree with your comments, lambda syntax is bizarre when you first see it. But that aside, I still find the std::sort syntax cleaner and more flexible than qsort since we can explicitly pass in the comparison function rather than a function pointer declared elsewhere and having to type cast a bunch of void*s. If anything this will be more akin to how we would make a device sort routine, by passing a .okl comparison function as a string. 

And, of course, this may all be moot later as we move more things to the device and replace std::sort instances. 

I'm not welded to this change, you can have final say. If you're ok with it, feel free to merge, otherwise you can close.

**Comment by tcew** [comment]
I’ll merge it given that this will mostly be replaced by on device sorts. Setting up a flexible device sort would be a good step forward.

I strongly recommend avoiding going further the down the C++ rabbit hole. Using iterators comes to mind as one trap that will make it tricky to offload.

**Pull request merged**
