### PR TITLE
[Libs] ParAlmond and libs updates

### PR DESCRIPTION
**Pull request by noelchalmers**
Large PR started over the long weekend. Here's the rundown:

- **ParAlmond code cleanup.** The parAlmond source naming and structure now matches the reset of the repo. It uses the linearSolver and linAlg modules for some operations which reduces the lib size.
- **PGMRES LinearSolver.** Extracted from parAlmond, moved to libs. 
- **OAS precon re-enabled.** Still somewhat experimental, but it's been added to unit tests as well.  
- **Removing usage of Platform comm.** The MPI_Comm in the platform is the 'global' comm on which the whole app is initialized. Modules like the mesh, timeSteppers, linearSolvers, etc., can be made on sub-communicators so I've removed usage of the platform comm everywhere necessary. 
- **BLAS interface cleanup** Just some clean up for interfacing to BLAS/LaPack and made it consistent throughout. 

This PR is the first step for several ParAlmond improvements in the pipeline.

### CODE REVIEW

**Comment by noelchalmers** [comment]
Cool to note that the last three bug fix commits were found using the unit tests. Very glad we added that.

**Comment by tcew** [comment]
LGTM. 

Does the AMG setup source need to be in a separate subdirectory ?

**Comment by tcew** [comment]
> Nope, just left it that way and can easily move it. Do you prefer it all in the /libs/parAlmond/ directory for consistency?

I think that is more consistent. Previously I had to think about which directory when looking...

**Comment by noelchalmers** [comment]
Will update, test, then merge.

**Comment by tcew** [comment]
Sounds good.

I think the new improvements help readability. 

Also the coverage seems to be up at 83+%

**Pull request merged**
