### PR TITLE
[Cubature][Hex][Quad] Fixing hex cubature and modifying quad cubature to work the same way

### PR DESCRIPTION
**Pull request by noelchalmers**
Hex cubature only fixed in INS. Drafting PR for early testing.

### CODE REVIEW

**Comment by tcew** [comment]
The renaming of operator arrays makes sense, and was overdue.

I am not sure how many libP branches this will impact. I would like to hear from @AliKarakus as well as @aaustin141

**Comment by noelchalmers** [comment]
Folks can checkout #37 for just the naming changes, and mesh cleanup. If people have branched off the last release or newer I think it should merge without major issue. When that gets merged, I'll force-push this PR to just be the hex cubature fixes (commit 
55498cd and later). If people are anxious to test the hex cubature they can checkout this draft PR without waiting.

**Comment by AliKarakus** [comment]
This will affect only levelset branch,and that is totally fine for my
side.

**Comment by noelchalmers** [comment]
This is ready for review once #37 gets the go-ahead.

**Comment by aaustin141** [comment]
The renaming wasn't an issue for any of the small changes I've made to INS.

**Pull request merged**
