### PR TITLE
[Solvers][Mesh] Add CFL condition calculation to solvers

### PR DESCRIPTION
**Pull request by noelchalmers**
This PR adds the ability in each time-dependent solver to properly calculate the CFL timestep restriction. Currently, all solvers will only do this calculation once, after the initial condition is set. Aside from being slightly more robust when starting timestepping, this may be useful in the future for some timesteppers to adapt the timestep size. 

This PR also addresses #25.

### CODE REVIEW

**Comment by tcew** [comment]
Using max velocity instead of dt ~ min(h/(lambda*N^2)) will be pessimistic

**Comment by noelchalmers** [comment]
Would you prefer calculating min(h/lambda) over all elements over computing min(h) and max(lambda)?

**Comment by tcew** [comment]
I think so. Sorry for not noticing that before.

**Comment by noelchalmers** [comment]
Sounds good. No reason we cant do that with a small tweak. I also need to update some golden norms. Some have shifted slightly enough that units tests are failing.

**Pull request merged**
