### PR TITLE
[Core][Libs] Platform class and reorganizing library structure

### PR DESCRIPTION
**Pull request by noelchalmers**
Adding a platform class which wraps some objects we tend to carry around everywhere. The platform class wraps the occa::device, base occa::properties, global settings, global MPI comm, and the linear algebra module. Since it's the first thing any solver will need to create, it also prints a cool libParanumal banner!

Some other noteworthy change:
- The buildKernel routine has been move to a method in the platform class. More compact and safe this way.
- A reference to a mesh object is no longer stored in the solver_t class. This is necessary in order to use things like the linearSolvers from parAlmond later, since parAlmond has no access to a underlying mesh. 

[Update] Libraries have been reorganized by merging the core directory with libs, and separating the timeStepper, linearSolver, and linAlg modules into their own libraries. The solver build systems have been simplified as a consequence.

### CODE REVIEW

**Comment by tcew** [comment]
The build is successful but the code coverage went down. 

I like the structuring.

Is this a good moment to pull the linAlg, timeStepper, and linearSolver into libs ?

**Comment by noelchalmers** [comment]
The drop in coverage is surprising. The change is largely cosmetic for argument passing. There were some code sections removed in ogs and paralmond where they were setting up the base occa::properties and they just find it in the platform class now. Maybe removing those sections dropped coverage.

Speaking of the linAlg, timeStepper, and linearSolver, I agree they should be put in separate folders so their modularity is implied. libs is starting to look a bit strange to me though. Moving these three modules would put something like >90% of the non-solver code in the libs folder, and core would only have a handful of src files. Does it make sense to instead combine libs and core, keeping the build system as it is? (I.e. make and link separate libs based on what the solver requests)

**Comment by tcew** [comment]
I agree that core and libs is a slightly odd partition.

I would say nuke code. Add libraries for timeStepper, linAlg, linearSolver to libs. The remainder could be libs/core

**Comment by noelchalmers** [comment]
ah ok that would work

**Comment by tcew** [comment]
LGTM. Squash & merge.

**Pull request merged**
